var classes = [
    {
        "name": "App\\Console\\Commands\\UpdatePeminjamanTerlambat",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Console\\Command",
            "App\\Models\\Data_Peminjaman"
        ],
        "parents": [
            "Illuminate\\Console\\Command"
        ],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 11,
        "volume": 44.97,
        "difficulty": 0.6,
        "effort": 26.98,
        "level": 1.67,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 74.95,
        "number_operators": 1,
        "number_operands": 12,
        "number_operators_unique": 1,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 65.57,
        "mIwoC": 65.57,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "App\\Console\\Commands\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Console\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "schedule",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "commands",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Console\\Kernel",
            "Illuminate\\Console\\Scheduling\\Schedule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Console\\Kernel"
        ],
        "implements": [],
        "lcom": 2,
        "length": 8,
        "vocabulary": 7,
        "volume": 22.46,
        "difficulty": 0.58,
        "effort": 13.1,
        "level": 1.71,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 38.5,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 2,
        "loc": 16,
        "lloc": 14,
        "mi": 91.44,
        "mIwoC": 65.4,
        "commentWeight": 26.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 9.13,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 18.25,
        "package": "App\\Console\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\AnggotaAuthVerifyRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 2,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0.67,
        "effort": 8,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 18,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 8,
        "loc": 20,
        "lloc": 12,
        "mi": 110.29,
        "mIwoC": 68.77,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "App\\Http\\Requests\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\RedirectIfAuthenticated",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Illuminate\\Auth\\Middleware\\RedirectIfAuthenticated",
            "Illuminate\\Http\\Request",
            "Closure",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "Illuminate\\Auth\\Middleware\\RedirectIfAuthenticated"
        ],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 9,
        "volume": 44.38,
        "difficulty": 1.29,
        "effort": 57.06,
        "level": 0.78,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 34.52,
        "number_operators": 5,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 5,
        "loc": 20,
        "lloc": 15,
        "mi": 97.38,
        "mIwoC": 62.41,
        "commentWeight": 34.97,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 6,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.15,
        "afferentCoupling": 8,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\AuthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "registrasi",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Anggota",
            "App\\Http\\Requests\\AnggotaAuthVerifyRequest",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 5,
        "length": 102,
        "vocabulary": 57,
        "volume": 594.95,
        "difficulty": 2.5,
        "effort": 1487.39,
        "level": 0.4,
        "bugs": 0.2,
        "time": 83,
        "intelligentContent": 237.98,
        "number_operators": 12,
        "number_operands": 90,
        "number_operators_unique": 3,
        "number_operands_unique": 54,
        "cloc": 4,
        "loc": 54,
        "lloc": 50,
        "mi": 63.3,
        "mIwoC": 42.84,
        "commentWeight": 20.46,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.62,
        "relativeSystemComplexity": 121.62,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 3.08,
        "totalSystemComplexity": 608.08,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\BukuController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Buku",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Facades\\Storage",
            "App\\Models\\Buku",
            "App\\Models\\Buku",
            "Illuminate\\Http\\Request",
            "App\\Models\\Buku",
            "Illuminate\\Support\\Facades\\Storage",
            "Illuminate\\Support\\Facades\\Storage",
            "Illuminate\\Support\\Str",
            "App\\Models\\Buku"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 6,
        "length": 214,
        "vocabulary": 68,
        "volume": 1302.72,
        "difficulty": 6.98,
        "effort": 9098.34,
        "level": 0.14,
        "bugs": 0.43,
        "time": 505,
        "intelligentContent": 186.53,
        "number_operators": 38,
        "number_operands": 176,
        "number_operators_unique": 5,
        "number_operands_unique": 63,
        "cloc": 21,
        "loc": 98,
        "lloc": 77,
        "mi": 69.36,
        "mIwoC": 36.5,
        "commentWeight": 32.86,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.39,
        "relativeSystemComplexity": 289.39,
        "totalStructuralComplexity": 1734,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 1736.33,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\DashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 78.06,
        "mIwoC": 78.06,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\PinjamController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "approve",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Data_Peminjaman",
            "App\\Models\\Data_Peminjaman",
            "App\\Models\\Data_Peminjaman",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Buku"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 110,
        "vocabulary": 41,
        "volume": 589.33,
        "difficulty": 8.85,
        "effort": 5217.31,
        "level": 0.11,
        "bugs": 0.2,
        "time": 290,
        "intelligentContent": 66.57,
        "number_operators": 24,
        "number_operands": 86,
        "number_operators_unique": 7,
        "number_operands_unique": 34,
        "cloc": 29,
        "loc": 83,
        "lloc": 54,
        "mi": 81.65,
        "mIwoC": 42,
        "commentWeight": 39.65,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 289.33,
        "totalStructuralComplexity": 867,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 868,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\AnggotaController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Anggota",
            "App\\Models\\Anggota"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 50,
        "vocabulary": 25,
        "volume": 232.19,
        "difficulty": 4.88,
        "effort": 1131.94,
        "level": 0.21,
        "bugs": 0.08,
        "time": 63,
        "intelligentContent": 47.63,
        "number_operators": 11,
        "number_operands": 39,
        "number_operators_unique": 5,
        "number_operands_unique": 20,
        "cloc": 5,
        "loc": 31,
        "lloc": 26,
        "mi": 81.3,
        "mIwoC": 52.16,
        "commentWeight": 29.14,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 100.36,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0.73,
        "totalSystemComplexity": 200.73,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\KembaliController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "approve",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Data_Peminjaman",
            "App\\Models\\Data_Peminjaman",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Buku",
            "App\\Models\\Data_Peminjaman",
            "Carbon\\Carbon"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 110,
        "vocabulary": 41,
        "volume": 589.33,
        "difficulty": 7.63,
        "effort": 4495.75,
        "level": 0.13,
        "bugs": 0.2,
        "time": 250,
        "intelligentContent": 77.25,
        "number_operators": 21,
        "number_operands": 89,
        "number_operators_unique": 6,
        "number_operands_unique": 35,
        "cloc": 29,
        "loc": 83,
        "lloc": 54,
        "mi": 81.79,
        "mIwoC": 42.14,
        "commentWeight": 39.65,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 196.33,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 589,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\User\\DashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "detail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pinjam",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Buku",
            "App\\Models\\Buku",
            "App\\Models\\Buku",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Data_Peminjaman"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 61,
        "vocabulary": 29,
        "volume": 296.34,
        "difficulty": 4.9,
        "effort": 1450.82,
        "level": 0.2,
        "bugs": 0.1,
        "time": 81,
        "intelligentContent": 60.53,
        "number_operators": 14,
        "number_operands": 47,
        "number_operators_unique": 5,
        "number_operands_unique": 24,
        "cloc": 4,
        "loc": 34,
        "lloc": 30,
        "mi": 75.4,
        "mIwoC": 50.07,
        "commentWeight": 25.34,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.45,
        "relativeSystemComplexity": 100.45,
        "totalStructuralComplexity": 300,
        "totalDataComplexity": 1.36,
        "totalSystemComplexity": 301.36,
        "package": "App\\Http\\Controllers\\User\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\User\\PinjamController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "return",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extend",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Data_Peminjaman",
            "App\\Models\\Data_Peminjaman",
            "Carbon\\Carbon",
            "App\\Models\\Data_Peminjaman",
            "Carbon\\Carbon",
            "Carbon\\Carbon"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 105,
        "vocabulary": 38,
        "volume": 551.03,
        "difficulty": 6.29,
        "effort": 3464.82,
        "level": 0.16,
        "bugs": 0.18,
        "time": 192,
        "intelligentContent": 87.63,
        "number_operators": 22,
        "number_operands": 83,
        "number_operators_unique": 5,
        "number_operands_unique": 33,
        "cloc": 24,
        "loc": 66,
        "lloc": 42,
        "mi": 84.8,
        "mIwoC": 44.59,
        "commentWeight": 40.21,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.35,
        "relativeSystemComplexity": 256.35,
        "totalStructuralComplexity": 768,
        "totalDataComplexity": 1.06,
        "totalSystemComplexity": 769.06,
        "package": "App\\Http\\Controllers\\User\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 8,
        "loc": 18,
        "lloc": 10,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\Anggota",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "dataPeminjaman",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "parents": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "implements": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 10,
        "volume": 36.54,
        "difficulty": 0.56,
        "effort": 20.3,
        "level": 1.8,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 65.77,
        "number_operators": 1,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 5,
        "loc": 17,
        "lloc": 12,
        "mi": 102.62,
        "mIwoC": 65.38,
        "commentWeight": 37.24,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.13,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Models\\Data_Peminjaman",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "anggota",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buku",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateLateFee",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model",
            "Carbon\\Carbon"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 26,
        "vocabulary": 15,
        "volume": 101.58,
        "difficulty": 4.25,
        "effort": 431.71,
        "level": 0.24,
        "bugs": 0.03,
        "time": 24,
        "intelligentContent": 23.9,
        "number_operators": 9,
        "number_operands": 17,
        "number_operators_unique": 5,
        "number_operands_unique": 10,
        "cloc": 9,
        "loc": 34,
        "lloc": 25,
        "mi": 90.82,
        "mIwoC": 55.05,
        "commentWeight": 35.77,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 16.8,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 2.4,
        "totalSystemComplexity": 50.4,
        "package": "App\\Models\\",
        "pageRank": 0.13,
        "afferentCoupling": 5,
        "efferentCoupling": 2,
        "instability": 0.29,
        "violations": {}
    },
    {
        "name": "App\\Models\\Buku",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 0,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 6,
        "lloc": 6,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Models\\",
        "pageRank": 0.09,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "Database\\Seeders\\DatabaseSeeder",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Seeder"
        ],
        "parents": [
            "Illuminate\\Database\\Seeder"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 6,
        "loc": 15,
        "lloc": 9,
        "mi": 212.52,
        "mIwoC": 171,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "Database\\Seeders\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Database\\Seeders\\BukuSeeder",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Illuminate\\Support\\Facades\\DB"
        ],
        "parents": [
            "Illuminate\\Database\\Seeder"
        ],
        "implements": [],
        "lcom": 1,
        "length": 66,
        "vocabulary": 34,
        "volume": 335.77,
        "difficulty": 0,
        "effort": 0,
        "level": 1.03,
        "bugs": 0.11,
        "time": 0,
        "intelligentContent": 345.95,
        "number_operators": 0,
        "number_operands": 66,
        "number_operators_unique": 0,
        "number_operands_unique": 34,
        "cloc": 5,
        "loc": 13,
        "lloc": 8,
        "mi": 103.46,
        "mIwoC": 62.48,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "Database\\Seeders\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Database\\Seeders\\AnggotaSeeder",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "App\\Models\\Anggota",
            "App\\Models\\Anggota",
            "App\\Models\\Anggota",
            "App\\Models\\Anggota",
            "App\\Models\\Anggota",
            "App\\Models\\Anggota",
            "App\\Models\\Anggota",
            "App\\Models\\Anggota"
        ],
        "parents": [
            "Illuminate\\Database\\Seeder"
        ],
        "implements": [],
        "lcom": 1,
        "length": 96,
        "vocabulary": 47,
        "volume": 533.24,
        "difficulty": 0,
        "effort": 0,
        "level": 0.98,
        "bugs": 0.18,
        "time": 0,
        "intelligentContent": 522.13,
        "number_operators": 0,
        "number_operands": 96,
        "number_operators_unique": 0,
        "number_operands_unique": 47,
        "cloc": 3,
        "loc": 18,
        "lloc": 15,
        "mi": 84.67,
        "mIwoC": 55.12,
        "commentWeight": 29.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "Database\\Seeders\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Database\\Seeders\\DataPeminjamanSeeder",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Carbon\\Carbon",
            "Illuminate\\Support\\Facades\\DB"
        ],
        "parents": [
            "Illuminate\\Database\\Seeder"
        ],
        "implements": [],
        "lcom": 1,
        "length": 61,
        "vocabulary": 30,
        "volume": 299.32,
        "difficulty": 3.69,
        "effort": 1105.18,
        "level": 0.27,
        "bugs": 0.1,
        "time": 61,
        "intelligentContent": 81.07,
        "number_operators": 13,
        "number_operands": 48,
        "number_operators_unique": 4,
        "number_operands_unique": 26,
        "cloc": 14,
        "loc": 32,
        "lloc": 18,
        "mi": 97.47,
        "mIwoC": 54.74,
        "commentWeight": 42.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 25,
        "package": "Database\\Seeders\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "anonymous@0000000000000a780000000000000000",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "implements": [],
        "lcom": 2,
        "length": 44,
        "vocabulary": 22,
        "volume": 196.21,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.07,
        "time": 0,
        "intelligentContent": 196.21,
        "number_operators": 0,
        "number_operands": 44,
        "number_operators_unique": 0,
        "number_operands_unique": 22,
        "cloc": 6,
        "loc": 32,
        "lloc": 26,
        "mi": 84.03,
        "mIwoC": 52.95,
        "commentWeight": 31.08,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 144,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 288,
        "package": "Database\\Seeders\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "anonymous@000000000000099a0000000000000000",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "implements": [],
        "lcom": 2,
        "length": 16,
        "vocabulary": 9,
        "volume": 50.72,
        "difficulty": 0,
        "effort": 0,
        "level": 1.13,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 16,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 6,
        "loc": 25,
        "lloc": 19,
        "mi": 94.44,
        "mIwoC": 60.03,
        "commentWeight": 34.41,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 81,
        "totalStructuralComplexity": 162,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 162,
        "package": "Database\\Seeders\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "anonymous@00000000000009610000000000000000",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "implements": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 10,
        "volume": 66.44,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 20,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 13,
        "loc": 34,
        "lloc": 21,
        "mi": 99.16,
        "mIwoC": 58.26,
        "commentWeight": 40.9,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 49,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 98,
        "package": "Database\\Seeders\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "anonymous@00000000000009640000000000000000",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "implements": [],
        "lcom": 2,
        "length": 19,
        "vocabulary": 9,
        "volume": 60.23,
        "difficulty": 0,
        "effort": 0,
        "level": 0.95,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 19,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 6,
        "loc": 28,
        "lloc": 22,
        "mi": 90.98,
        "mIwoC": 58.12,
        "commentWeight": 32.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 128,
        "package": "Database\\Seeders\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Database\\Factories\\UserFactory",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "definition",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unverified",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Factories\\Factory",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Str"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Factories\\Factory"
        ],
        "implements": [],
        "lcom": 2,
        "length": 13,
        "vocabulary": 10,
        "volume": 43.19,
        "difficulty": 1.25,
        "effort": 53.98,
        "level": 0.8,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 34.55,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 14,
        "loc": 27,
        "lloc": 13,
        "mi": 109.02,
        "mIwoC": 64.12,
        "commentWeight": 44.91,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.57,
        "totalSystemComplexity": 72.57,
        "package": "Database\\Factories\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Database\\Factories\\AnggotaFactory",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "definition",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Factories\\Factory"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Factories\\Factory"
        ],
        "implements": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 8,
        "volume": 33,
        "difficulty": 0.71,
        "effort": 23.57,
        "level": 1.4,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 46.2,
        "number_operators": 1,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 7,
        "loc": 22,
        "lloc": 15,
        "mi": 101.92,
        "mIwoC": 63.58,
        "commentWeight": 38.34,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 25.17,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.17,
        "totalSystemComplexity": 25.17,
        "package": "Database\\Factories\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]